"use client";
import {useMemo,useState} from "react";
import {LayoutDashboard,ShoppingBag,WalletCards,Package,Building2,CircleDollarSign,Users,Settings,Plane,Plus,Menu,Search,CalendarDays,TrendingUp,ReceiptText,CreditCard,BarChart3,ArrowUpRight,Megaphone,BellRing,MessageCircle,Upload,UserPlus,MapPin,BookOpen,BadgePercent} from "lucide-react";
import {Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";

const nav=[["Visão geral",LayoutDashboard],["Vendas",ShoppingBag],["Viagens",Plane],["Marketing",Megaphone],["Financeiro",WalletCards],["Produtos",Package],["Fornecedores",Building2],["Regras comerciais",BookOpen],["Comissões",CircleDollarSign],["Equipe",Users],["Configurações",Settings]] as const;
const rows=[
 {id:"VB-1084",client:"Mariana Costa",product:"Gramado • Natal Luz",seller:"Ana Paula",value:8940,status:"Confirmada"},
 {id:"VB-1083",client:"Rafael Mendes",product:"Cruzeiro MSC Seaview",seller:"Gustavo",value:12480,status:"A receber"},
 {id:"VB-1082",client:"Camila Andrade",product:"Pacote Porto Seguro",seller:"Ana Paula",value:5360,status:"Confirmada"},
 {id:"VB-1081",client:"Bruno e família",product:"Disney • Orlando",seller:"Gustavo",value:18900,status:"Em negociação"}];
const monthly=[{m:"Abr",v:38},{m:"Mai",v:52},{m:"Jun",v:46},{m:"Jul",v:67},{m:"Ago",v:73},{m:"Set",v:61}];
const mix=[{name:"Pacotes",value:44,color:"#0e7490"},{name:"Aéreo",value:29,color:"#f59e0b"},{name:"Hotel",value:17,color:"#2563eb"},{name:"Outros",value:10,color:"#cbd5e1"}];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});

export default function Home(){
 const [active,setActive]=useState("Visão geral"),[mobile,setMobile]=useState(false),[query,setQuery]=useState("");
 const filtered=useMemo(()=>rows.filter(x=>Object.values(x).join(" ").toLowerCase().includes(query.toLowerCase())),[query]);
 return <main><aside className={mobile?"sidebar open":"sidebar"}>
  <div className="brand"><span><Plane/></span><div><b>Viaje Bem</b><small>GESTÃO</small></div></div>
  <nav>{nav.map(([label,Icon])=><button key={label} className={label===active?"active":""} onClick={()=>{setActive(label);setMobile(false)}}><Icon/>{label}</button>)}</nav>
  <div className="profile"><i>GS</i><div><b>Gustavo Santos</b><small>Administrador</small></div></div>
 </aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>}
 <section className="workspace"><header><Button variant="ghost" size="icon" className="hamb" onClick={()=>setMobile(true)}><Menu/></Button><div><small>Viaje Bem Agência de Viagens</small><h1>{active}</h1></div><div className="actions"><span><CalendarDays/> Setembro 2026</span><SaleDialog/></div></header>
 <div className="content">{active==="Visão geral"?<Dashboard query={query} setQuery={setQuery} rows={filtered}/>:active==="Marketing"?<Marketing/>:active==="Viagens"?<Trips/>:active==="Equipe"?<Team/>:active==="Configurações"?<AgencySettings/>:active==="Regras comerciais"?<CommercialRules/>:<Module title={active}/>}</div></section></main>
}

function SaleDialog(){return <Dialog><DialogTrigger render={<Button className="primary"><Plus/> Nova venda</Button>}/><DialogContent><DialogHeader><DialogTitle>Registrar nova venda</DialogTitle><DialogDescription>Cadastre os dados principais. Parcelas e comissões serão configuradas na próxima etapa.</DialogDescription></DialogHeader><div className="form"><label>Cliente<Input placeholder="Nome do cliente"/></label><label>Produto<Input placeholder="Pacote ou serviço"/></label><label>Valor total<Input placeholder="R$ 0,00"/></label><label>Vendedor<Input placeholder="Responsável"/></label></div><div className="form-actions"><Button variant="outline">Salvar rascunho</Button><Button className="primary">Continuar</Button></div></DialogContent></Dialog>}

function Dashboard({query,setQuery,rows}:{query:string;setQuery:(s:string)=>void;rows:any[]}){
 return <><div className="welcome"><div><h2>Bom dia, Gustavo</h2><p>Acompanhe o desempenho comercial e financeiro da agência.</p></div><span><TrendingUp/> Meta mensal: 81%</span></div>
 <div className="metrics"><Metric Icon={CircleDollarSign} label="Vendas no mês" value="R$ 61.420" note="+12,8%"/><Metric Icon={ReceiptText} label="Recebimentos" value="R$ 48.760" note="+8,4%"/><Metric Icon={CreditCard} label="Pagamentos" value="R$ 35.190" note="63% do previsto"/><Metric Icon={BarChart3} label="Ticket médio" value="R$ 6.824" note="+5,1%"/></div>
 <div className="charts"><article className="panel"><Title title="Evolução das vendas" sub="Valores em milhares de reais"/><div className="chart"><ResponsiveContainer><BarChart data={monthly} margin={{left:-18}}><CartesianGrid vertical={false} stroke="#e8edf4"/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="v" fill="#0e7490" radius={[6,6,2,2]} barSize={30}/></BarChart></ResponsiveContainer></div></article>
 <article className="panel"><Title title="Produtos vendidos" sub="Participação por categoria"/><div className="mix"><div className="donut"><ResponsiveContainer><PieChart><Pie data={mix} dataKey="value" innerRadius={52} outerRadius={75} paddingAngle={3}>{mix.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><b>18<small>vendas</small></b></div><div className="legend">{mix.map(x=><p key={x.name}><i style={{background:x.color}}/>{x.name}<b>{x.value}%</b></p>)}</div></div></article></div>
 <div className="bottom"><article className="panel"><Title title="Vendas recentes" sub="Últimas movimentações da equipe"/><div className="search"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente ou produto..."/></div><div className="table"><table><thead><tr><th>Venda</th><th>Cliente / produto</th><th>Responsável</th><th>Valor</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.id}</b></td><td><b>{x.client}</b><small>{x.product}</small></td><td>{x.seller}</td><td><b>{money(x.value)}</b></td><td><em className={x.status.replaceAll(" ","-").toLowerCase()}>{x.status}</em></td></tr>)}</tbody></table></div></article>
 <aside className="panel attention"><Title title="Atenção hoje" sub="Pendências prioritárias"/><Task Icon={WalletCards} title="3 recebimentos vencem hoje" sub="R$ 7.830 previstos"/><Task Icon={CircleDollarSign} title="Comissões para aprovar" sub="5 lançamentos • R$ 2.460"/><Task Icon={TrendingUp} title="Meta da equipe" sub="Faltam R$ 14.580 para 100%"/></aside></div></>
}
function Metric({Icon,label,value,note}:any){return <article className="metric"><span><Icon/></span><div><p>{label}</p><b>{value}</b><small>{note}</small></div></article>}
function Title({title,sub}:{title:string;sub:string}){return <div className="title"><h3>{title}</h3><p>{sub}</p></div>}
function Task({Icon,title,sub}:any){return <div className="task"><span><Icon/></span><div><b>{title}</b><small>{sub}</small></div><ArrowUpRight/></div>}
const modules:Record<string,[string,string,any][]>={
 "Vendas":[["Nova venda","Cliente, produtos, parcelas e participantes.",ShoppingBag],["Pipeline comercial","Propostas, negociações e confirmações.",TrendingUp],["Histórico","Todas as vendas e alterações.",ReceiptText]],
 "Financeiro":[["Contas a receber","Parcelas, vencimentos e baixas.",WalletCards],["Contas a pagar","Fornecedores e despesas.",CreditCard],["Fluxo de caixa","Entradas, saídas e saldo projetado.",BarChart3]],
 "Produtos":[["Pacotes e serviços","Aéreo, hotel, passeios, seguros e pacotes.",Package],["Categorias","Catálogo para relatórios e comissões.",ShoppingBag]],
 "Fornecedores":[["Consolidadoras","Condições, prazos e contatos.",Building2],["Operadoras","Fornecedores ligados aos produtos.",Plane]],
 "Comissões":[["Regras de comissão","Percentuais por produto, agência e função.",Settings],["Divisão por venda","Vendedor e colaboradores participantes.",Users],["Aprovações","Revise antes do pagamento.",CircleDollarSign]],
};
function Module({title}:{title:string}){return <div><div className="module-head"><div><h2>{title}</h2><p>Gerencie esta área de forma centralizada e segura.</p></div><Button className="primary"><Plus/> Adicionar</Button></div><div className="cards">{(modules[title]||[]).map(([name,desc,Icon])=><article key={name}><span><Icon/></span><h3>{name}</h3><p>{desc}</p><button>Acessar <ArrowUpRight/></button></article>)}</div></div>}

function Marketing(){return <div><div className="module-head"><div><h2>Marketing e aquisição</h2><p>Compare investimento em mídia com os clientes e vendas gerados.</p></div><Button className="primary"><Plus/> Nova campanha</Button></div><div className="metrics"><Metric Icon={Megaphone} label="Investimento no mês" value="R$ 4.250" note="Google + Meta"/><Metric Icon={Users} label="Leads gerados" value="186" note="R$ 22,85 por lead"/><Metric Icon={ShoppingBag} label="Vendas atribuídas" value="14" note="7,5% de conversão"/><Metric Icon={TrendingUp} label="Retorno sobre anúncios" value="6,4x" note="R$ 27.180 em vendas"/></div><article className="panel section-gap"><Title title="Desempenho das campanhas" sub="Do anúncio até a venda confirmada"/><div className="campaign-row"><b>Gramado Natal Luz • Google Ads</b><span>83 leads</span><span>7 vendas</span><strong>ROAS 7,2x</strong></div><div className="campaign-row"><b>Férias em família • Instagram</b><span>61 leads</span><span>4 vendas</span><strong>ROAS 5,8x</strong></div><div className="campaign-row"><b>Cruzeiros 2027 • Meta Ads</b><span>42 leads</span><span>3 vendas</span><strong>ROAS 5,1x</strong></div></article></div>}

function Trips(){return <div><div className="module-head"><div><h2>Acompanhamento de viagens</h2><p>Histórico do cliente, próximos embarques e lembretes importantes.</p></div><Button className="primary"><Plus/> Criar alerta</Button></div><div className="trip-grid"><article className="panel trip-card"><span className="trip-date"><b>16</b>DEZ</span><div><h3>Mariana Costa • Gramado</h3><p><MapPin/> Hotel Chocoland • 4 viajantes</p><small>Venda VB-1084 • 16 a 22 de dezembro</small></div><em>Em 97 dias</em></article><article className="panel trip-card"><span className="trip-date blue"><b>28</b>SET</span><div><h3>Rafael Mendes • Cruzeiro MSC</h3><p><MapPin/> Porto do Rio • 2 viajantes</p><small>Venda VB-1083 • 28 de setembro a 5 de outubro</small></div><em>Em 18 dias</em></article></div><div className="bottom"><article className="panel"><Title title="Próximos lembretes" sub="Alertas automáticos vinculados às viagens"/><Task Icon={BellRing} title="Check-in de Rafael abre amanhã às 14h" sub="Enviar lembrete para cliente e agência"/><Task Icon={Plane} title="Voo de Mariana em 16/12 às 09h20" sub="Lembrar 48h e 4h antes do embarque"/><Task Icon={ReceiptText} title="Seguro viagem pendente" sub="Bruno e família • Orlando"/></article><article className="panel whatsapp"><MessageCircle/><h3>Central de WhatsApp</h3><p>Envie confirmações, alertas de check-in, documentos e lembretes usando os modelos da agência.</p><Button className="whatsapp-btn">Preparar mensagem</Button></article></div></div>}

function Team(){return <div><div className="module-head"><div><h2>Equipe e usuários</h2><p>Somente administradores podem criar usuários e alterar permissões.</p></div><UserDialog/></div><article className="panel"><Title title="Usuários da agência" sub="Acessos limitados à Viaje Bem"/><div className="user-row"><i>GS</i><div><b>Gustavo Santos</b><small>gustavo@agviajebem.com.br</small></div><span>Administrador</span><em>Ativo</em></div><div className="user-row"><i>AP</i><div><b>Ana Paula</b><small>ana@agviajebem.com.br</small></div><span>Vendedora</span><em>Ativo</em></div><div className="user-row"><i>MF</i><div><b>Marcos Ferreira</b><small>marcos@agviajebem.com.br</small></div><span>Financeiro</span><em>Ativo</em></div></article></div>}
function UserDialog(){return <Dialog><DialogTrigger render={<Button className="primary"><UserPlus/> Criar usuário</Button>}/><DialogContent><DialogHeader><DialogTitle>Novo usuário da agência</DialogTitle><DialogDescription>O usuário receberá um convite para definir a própria senha.</DialogDescription></DialogHeader><div className="form"><label>Nome completo<Input placeholder="Nome do usuário"/></label><label>E-mail<Input type="email" placeholder="usuario@agencia.com.br"/></label><label>Perfil<Input placeholder="Administrador, vendedor..."/></label><label>Comissão padrão<Input placeholder="0,00%"/></label></div><div className="form-actions"><Button variant="outline">Cancelar</Button><Button className="primary">Enviar convite</Button></div></DialogContent></Dialog>}

function AgencySettings(){return <div><div className="module-head"><div><h2>Configurações da agência</h2><p>Personalize a marca, comunicação e políticas da sua empresa.</p></div><Button className="primary">Salvar alterações</Button></div><div className="settings-grid"><article className="panel logo-panel"><Title title="Identidade visual" sub="A marca aparecerá no sistema e nos documentos enviados"/><div className="logo-preview"><Plane/><b>Viaje Bem</b></div><Button variant="outline"><Upload/> Enviar logotipo</Button><small>PNG, JPG ou SVG • fundo transparente recomendado</small></article><article className="panel"><Title title="Dados e WhatsApp da agência" sub="Somente administradores podem alterar estes dados"/><div className="form"><label>Nome da agência<Input defaultValue="Viaje Bem"/></label><label>CNPJ<Input placeholder="00.000.000/0000-00"/></label><label>WhatsApp remetente<Input defaultValue="+55 21 99999-9999"/></label><label>E-mail<Input defaultValue="atendimento@agviajebem.com.br"/></label><label className="wide-label">Mensagem padrão de lembrete<Input defaultValue="Olá, {cliente}! Temos um lembrete importante sobre sua viagem."/></label></div><small>O telefone do cliente é preenchido no cadastro e pode ser confirmado em cada viagem.</small></article></div></div>}

const commercialRules=[
 {name:"GOL",type:"Companhia aérea",use:"Somente aéreo",installments:"5x sem juros",commission:"0%",rav:"Permitido",updated:"08 set 2026"},
 {name:"LATAM",type:"Companhia aérea",use:"Somente aéreo",installments:"7x sem juros",commission:"0%",rav:"Permitido",updated:"05 set 2026"},
 {name:"Azul",type:"Companhia aérea",use:"Somente aéreo",installments:"10x sem juros",commission:"0%",rav:"Permitido",updated:"02 set 2026"},
 {name:"RCA",type:"Consolidadora",use:"Pacotes",installments:"10x sem juros",commission:"8%",rav:"Configurável",updated:"09 set 2026"},
 {name:"MSC",type:"Operadora",use:"Cruzeiros",installments:"10x sem juros",commission:"10%",rav:"Configurável",updated:"01 set 2026"}];
function CommercialRules(){return <div><div className="module-head"><div><h2>Regras comerciais</h2><p>Consulta rápida de parcelamento, comissão e RAV por fornecedor.</p></div><RuleDialog/></div><div className="metrics"><Metric Icon={BadgePercent} label="RAV lançado no mês" value="R$ 3.840" note="18 vendas"/><Metric Icon={CircleDollarSign} label="Comissões previstas" value="R$ 7.260" note="+9,3% no mês"/><Metric Icon={ShoppingBag} label="Vendas com RAV" value="62%" note="11 de 18 vendas"/><Metric Icon={TrendingUp} label="Impacto na margem" value="+6,2%" note="RAV sobre receita"/></div><article className="panel section-gap"><div className="rule-head"><Title title="Manual de operações" sub="Regras vigentes para consulta dos agentes"/><Input placeholder="Buscar companhia ou consolidadora..."/></div><div className="table"><table><thead><tr><th>Fornecedor</th><th>Aplicação</th><th>Parcelamento</th><th>Comissão</th><th>RAV</th><th>Atualização</th></tr></thead><tbody>{commercialRules.map(r=><tr key={r.name}><td><b>{r.name}</b><small>{r.type}</small></td><td>{r.use}</td><td><b>{r.installments}</b></td><td>{r.commission}</td><td><em className="rav-tag">{r.rav}</em></td><td>{r.updated}</td></tr>)}</tbody></table></div></article><div className="bottom"><article className="panel"><Title title="Impacto mensal do RAV" sub="Valor adicional por consolidadora"/><div className="rav-row"><b>RCA</b><span>8 vendas</span><strong>R$ 1.920</strong></div><div className="rav-row"><b>MSC</b><span>3 vendas</span><strong>R$ 1.180</strong></div><div className="rav-row"><b>Outros</b><span>7 vendas</span><strong>R$ 740</strong></div></article><article className="panel"><Title title="Como o cálculo funciona" sub="Visibilidade na montagem da venda"/><p className="explanation">A venda registra separadamente o valor do fornecedor, a comissão recebida e o RAV cobrado. Assim, o agente vê a margem prevista antes de confirmar e o gestor acompanha o impacto real no fechamento mensal.</p></article></div></div>}
function RuleDialog(){return <Dialog><DialogTrigger render={<Button className="primary"><Plus/> Nova regra</Button>}/><DialogContent><DialogHeader><DialogTitle>Nova regra comercial</DialogTitle><DialogDescription>Defina a condição vigente. Regras antigas permanecem no histórico.</DialogDescription></DialogHeader><div className="form"><label>Fornecedor<Input placeholder="Companhia, consolidadora..."/></label><label>Aplicação<Input placeholder="Somente aéreo, pacote..."/></label><label>Máximo de parcelas<Input placeholder="10"/></label><label>Juros<Input placeholder="Sem juros"/></label><label>Comissão<Input placeholder="0,00%"/></label><label>RAV<Input placeholder="Valor ou percentual"/></label><label>Início da vigência<Input type="date"/></label><label>Observações<Input placeholder="Condições e exceções"/></label></div><div className="form-actions"><Button variant="outline">Cancelar</Button><Button className="primary">Salvar regra</Button></div></DialogContent></Dialog>}
